# Default values for API
replicaCount: 1

image:
  repository: ghcr.io/mcce2024/argo-g1-api
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# Environment variables
env:
  TENANT_ID: "default" # Default tenant ID, can be overridden per deployment

# External Database configuration (Aiven Cloud)
database:
  host: "inenpt-g1-postgresql-exoscale-43335956-5350-4ab0-9b26-1f870f09d.j.aivencloud.com"
  port: 21699
  name: "defaultdb"
  user: "avnadmin"
  password: "" # Set via sealed secret
  ssl: "require"
  caCertConfigMap: "ca-certificate" # ConfigMap containing ca.pem
  # CA Certificate content - will be populated by setup script or manually
  caCert: |
    -----BEGIN CERTIFICATE-----
    MIIEUDCCArigAwIBAgIUUdB15YE5OlwzG9L4cbsi26Wgo4QwDQYJKoZIhvcNAQEM
    BQAwQDE+MDwGA1UEAww1MTIxNDdiYmItZTQ2My00ZTQ5LWFjY2MtMGUzMjEwYzBm
    MGEwIEdFTiAxIFByb2plY3QgQ0EwHhcNMjUwNzA0MTc0MjQyWhcNMzUwNzAyMTc0
    MjQyWjBAMT4wPAYDVQQDDDUxMjE0N2JiYi1lNDYzLTRlNDktYWNjYy0wZTMyMTBj
    MGYwYTAgR0VOIDEgUHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCC
    AYoCggGBAN7svtOmLql7GdhPJXMaSPgMLS9y2ceIBve4+kAZWShNg5tabSU7ZQ/T
    uQcm6rrOluYMaYjs+cwJv4WqF6fqpdDiSxMhDWXe6jSWCF17leyHMYQf/qBWj9+I
    ybbAZ9ufhNbraE6FmBGmI07HoaZ9SpJ84urS0k1fec2cYfwnKhFw46jJbXD7oriD
    1ma5RxPbQurte7xw19luaa09/zTu7yfIjWSmjRQWOO4+owbUBFzaioyDWWhvtb9O
    w1hoy2uDhmIi12J3iNTSSmOD6gXLDpDx4qheAXLd/bSk9G1ckRasblHf0+FZaTXQ
    zQRlJEUjEPQOJAIlkTQZd3+fZb9+AyWOwmf92P07lukVCpybqaDFMcHU3+RQN4+e
    CgLNLW6tp3L0kQcUr99pk77OzSg0ON3T7CO9mfwLCmLzvhZRau7pfz4zHaG5UDy+
    FSxZtN/v5KnMJA9FKxj48kEmgFn/AlNHjsbLBe4TE1A0aXg/ICMNLcwLwapaYjkO
    S3QNXaQVwwIDAQABo0IwQDAdBgNVHQ4EFgQU7F7ENjvhd3HerrogxoDCnOmzv1ow
    EgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQAD
    ggGBADqjJeeMyNw0vVFuZdI5LjFl5H30FkRTyxeZ28X/gn0eScbz0rkB19Ab3EGn
    PR7Jie1aB6peTj+FVdsRqj5LquS+48WzwppfvbwhrJRx1yF1LSmW/4ARrgbRV1Is
    duaMdSmNsJBU6M89wnvoPwT0uNBZoI8fbrHlwrcI8pIQ1uZbIqGQUYJEVQocqMbW
    cRkVbK0Sw/RlRlLHH627u9RLtC/yHz+xiJk4sJWYQPZ3cW7Y81FxJHBA24lsOcqs
    qeVae6lcuWW07jFiGlE+i8pAAdVH05s9y9cWxX/+SudfPDGy+xeH+k+9sTfnMJIj
    7XLWlRPwADaPWyAguFH+Vpm0jy8wv0sMXdpDHBVkHuBLUMb/qBF1Lt5Q31q439LT
    wxQLaOxHMEoZ4uQhnpe9U5m2vex/XFa7nasdv7kia2MR21xewBO4QjwTfXvx2dB/
    NW/gZKs4XvWU7p8W+5W9yVfWkZj6IW7IUkZjcE1OTNerblp92p9+rIRQ/tAQEn7Y
    d3Ytkw==
    -----END CERTIFICATE-----
# Application configuration
app:
  port: 3000
  nodeEnv: "production"
  logLevel: "info"

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
