apiVersion: v1
kind: Secret
metadata:
  name: {{ include "producer.fullname" . }}-github-token
  labels:
    {{- include "producer.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc | quote }}