apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
  labels:
    app: api-service
    component: api
spec:
  project: default
  source:
    repoURL: https://github.com/MCCE2024/INENPT-G1-Argo.git
    targetRevision: main
    path: applications/api/helm
    helm:
      values: |
        database:
          host: "inenpt-g1-postgresql-exoscale-8d4daa3a-4052-4544-b383-b09812875.b.aivencloud.com"
          port: 21699
          name: "defaultdb"
          user: "avnadmin"
          password: ""  # Will be set via secret
          ssl: "require"
        github:
          clientId: ""  # Will be set via secret
          clientSecret: ""  # Will be set via secret
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
