apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: api-service
  namespace: mcce-g1-prod

resources:
  - deployment.yaml
  - argocd-application.yaml

commonLabels:
  app: api-service
  component: api
  version: v1.0.0

namespace: mcce-g1-prod
