apiVersion: v2
name: producer
description: A Helm chart for the producer service that sends datetime messages to the API (which stores them in PostgreSQL)
type: application
version: 0.2.0
appVersion: "2.0.0"
keywords:
  - producer
  - api
  - postgresql
  - cronjob
home: https://github.com/MCCE2024/INENPT-G1-Argo
sources:
  - https://github.com/MCCE2024/INENPT-G1-Argo
maintainers:
  - name: Group1
    email: group1@example.com
