apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer
  namespace: argocd
  annotations:
    # Enable automatic image updates with digest strategy
    argocd-image-updater.argoproj.io/image-list: producer=ghcr.io/mcce2024/argo-g1-producer:latest
    argocd-image-updater.argoproj.io/producer.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MCCE2024/INENPT-G1-Argo.git
    targetRevision: main
    path: applications/producer/helm
    helm:
      values: |
        api:
          url: "http://api-service:80"
          timeout: 30
        github:
          token: ""  # Leave empty here; set via secret in the cluster
        environment: "prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
