# Default values for consumer
replicaCount: 1

image:
  repository: ghcr.io/mcce2024/argo-g1-consumer
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# Tenant configuration
tenant:
  name: "tenant-a" # Will be overridden per deployment
  port: 30000 # Will be overridden per deployment

# Service configuration
service:
  type: NodePort
  port: 3000
  targetPort: 3000

# GitHub OAuth configuration
github:
  clientId: "" # Will be set via secret
  clientSecret: "" # Will be set via secret

# API configuration
api:
  baseUrl: "http://api-service:3000"

# Session configuration
session:
  secret: "" # Will be set via secret

# Resource limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
