apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer
  namespace: argocd
  annotations:
    # Enable automatic image updates with digest strategy
    argocd-image-updater.argoproj.io/image-list: consumer=ghcr.io/mcce2024/argo-g1-consumer:latest
    argocd-image-updater.argoproj.io/consumer.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MCCE2024/INENPT-G1-Argo.git
    targetRevision: main
    path: applications/consumer/helm
    helm:
      values: |
        tenant:
          name: "tenant-a"
          port: 30000
        github:
          clientId: ""  # Will be set via secret
          clientSecret: ""  # Will be set via secret
        session:
          secret: ""  # Will be set via secret
  destination:
    server: https://kubernetes.default.svc
    namespace: test-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
