apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: api-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBd6Qe/buaiEAyni3AWqn545D7gUasl9JkxQgt3C9r5SlynlQWMQNffdA3VYl4h4eRaGRAI/E9yx/xsfqFMZGZ8hORr7wTtGcUPIjjvQrBYRtzDdSMcwtQu4O6O7R/5Dt3WH4o06aa8MRE7F57OKG/v3c6S4f0SgPW03mizSvmkAls/N0RhaDlvs2ELBGJVlPvr0ldIEgPnNASLIrraFe6VYYn6oCgQWPueUShU15mLj5aMB+0GNXMHLnvjj/FOsc53FfiAk//VLGgZaFwzfCJ6+Etjdwv3qq1f8t17431G+sJnW20RrzLQL6S148vfgshHjuA2Fm6LWdhVLANthWlwWIsB4TAwHurBTNb9wx1zvxEIegAAELC2/urIvToex+UMXVBXDIinBNF1exCKbKDGNY+IuTyC7JiefcsJvM06WivHA4fKYRGfOp0Zc82dnC7XbbJFs81VHug+KlFlI9nE4wwEwVK3qcHjiL4IDHrFpS3Ike2LJ5UfNUzE9YdQTd/eIKK9Sq8SzjX7sF3L2Pii6OoIzukJNUDGITNfCWg1GTtJp5G+6YqEMHgy5npl2JJ4TNHU2qWd7H1iepuhcdCO4ATOOZik65jLMhy0Ioy+tEWeBVuWmwOktHVhlRgw7cwDNNQg7doGuYk5cBGbGucSdGE9t3MWoCd39DJfTTYap7ihTkvG40yGpa2RiL2dXQCLVDR7VXSg1A26eIlUZc5Z5JVSZKueN78=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: api-db-secret
      namespace: default
---
